### ISSUE TITLE
您好，ui和ui2之间的接口怎么相互调用 ？

### ISSUE THREAD

**Issue by IKangXu** [chengjiansheng/cjs-oauth2-example#2]
很急

**Comment by chengjiansheng** [comment]
@kangxukangxu 没太明白你的意思，ui和ui2之间的接口调用会有什么问题吗？ui和ui2是内部的两个服务，它们之间调用没有必要用OAuth2了吧

**Comment by IKangXu** [comment]
就是现在ui有一套服务，ui2是一套服务，如果分布式部署的时候，ui想调用ui2里面的一些接口获取数据，那么怎么实现？  现在有oauth2做了限制。



1454900516@qq.com
 
发件人： chengjiansheng
发送时间： 2018-09-14 18:09
收件人： chengjiansheng/cjs-oauth2-example
抄送： kangxu-nigel; Mention
主题： Re: [chengjiansheng/cjs-oauth2-example] 您好，ui和ui2之间的接口怎么相互调用 ？ (#2)
@kangxukangxu 没太明白你的意思，ui和ui2之间的接口调用会有什么问题吗？ui和ui2是内部的两个服务，它们之间调用没有必要用OAuth2了吧

**Comment by IKangXu** [comment]
您好，您那边有什么好的解决办法吗 ？


1454900516@qq.com
 
发件人： chengjiansheng
发送时间： 2018-09-14 18:09
收件人： chengjiansheng/cjs-oauth2-example
抄送： kangxu-nigel; Mention
主题： Re: [chengjiansheng/cjs-oauth2-example] 您好，ui和ui2之间的接口怎么相互调用 ？ (#2)
@kangxukangxu 没太明白你的意思，ui和ui2之间的接口调用会有什么问题吗？ui和ui2是内部的两个服务，它们之间调用没有必要用OAuth2了吧

**Comment by 852675742** [comment]
可以用feign调用吧，内部系统
